# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build Job1
    - bash: echo $(PipelineLevelVariable)
  - job: SecondJob
    steps:
    - bash: echo Build Job2    
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment) DevDeploy Job1
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo QADeploy Job1
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo ProdDeploy Job1



